export const initialState = {
  products: {
    data: [
      {
        id: 1,
        name: 'Excellent Jeans 1',
        price: '$50',
        imageOne: '/images/products/Jeans-1-1.webp',
        imageTwo: '/images/products/Jeans-1-2.webp',
        imageThree: '/images/products/Jeans-1-3.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 2,
        name: 'Excellent Jeans 2',
        price: '$70',
        imageOne: '/images/products/Jeans-2-1.webp',
        imageTwo: '/images/products/Jeans-2-2.webp',
        imageThree: '/images/products/Jeans-2-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 3,
        name: 'Excellent Jeans 3',
        price: '$55',
        imageOne: '/images/products/Jeans-3-1.webp',
        imageTwo: '/images/products/Jeans-3-2.webp',
        imageThree: '/images/products/Jeans-3-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 4,
        name: 'Excellent Jeans 4',
        price: '$75',
        imageOne: '/images/products/Jeans-4-1.webp',
        imageTwo: '/images/products/Jeans-4-2.webp',
        imageThree: '/images/products/Jeans-4-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 5,
        name: 'Excellent Jeans 5',
        price: '$65',
        imageOne: '/images/products/Jeans-5-1.webp',
        imageTwo: '/images/products/Jeans-5-2.webp',
        imageThree: '/images/products/Jeans-5-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 6,
        name: 'Excellent Jeans 6',
        price: '$85',
        imageOne: '/images/products/Jeans-6-1.webp',
        imageTwo: '/images/products/Jeans-6-2.webp',
        imageThree: '/images/products/Jeans-6-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 7,
        name: 'Excellent Jeans 7',
        price: '$50',
        imageOne: '/images/products/Jeans-7-1.webp',
        imageTwo: '/images/products/Jeans-7-2.webp',
        imageThree: '/images/products/Jeans-7-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 8,
        name: 'Excellent Jeans 8',
        price: '$60',
        imageOne: '/images/products/Jeans-8-1.webp',
        imageTwo: '/images/products/Jeans-8-2.webp',
        imageThree: '/images/products/Jeans-8-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 9,
        name: 'Excellent Jeans 9',
        price: '$55',
        imageOne: '/images/products/Jeans-9-1.webp',
        imageTwo: '/images/products/Jeans-9-2.webp',
        imageThree: '/images/products/Jeans-9-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 10,
        name: 'Excellent Jeans 10',
        price: '$80',
        imageOne: '/images/products/Jeans-10-1.webp',
        imageTwo: '/images/products/Jeans-10-2.webp',
        imageThree: '/images/products/Jeans-10-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 11,
        name: 'Excellent Jeans 11',
        price: '$75',
        imageOne: '/images/products/Jeans-11-1.jpg',
        imageTwo: '/images/products/Jeans-11-2.webp',
        imageThree: '/images/products/Jeans-11-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
      {
        id: 12,
        name: 'Excellent Jeans 12',
        price: '$100',
        imageOne: '/images/products/Jeans-12-1.webp',
        imageTwo: '/images/products/Jeans-12-2.webp',
        imageThree: '/images/products/Jeans-12-3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu tellus consectetur, vehicula velit non, convallis arcu. Morbi ut nibh egestas, ullamcorper erat eu, convallis urna. Integer sollicitudin sapien convallis, scelerisque ex id, maximus nisl. Pellentesque nec mauris ac est faucibus porta sit amet in elit. Quisque eleifend pellentesque imperdiet. Praesent euismod lectus non ante porttitor efficitur. Sed pretium tortor.',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
